### PR TITLE
RSpec/MetadataStyle: Fix false positive for multiple strings preceding metadata

### LINKED ISSUE #1714: RSpec/MetadataStyle: False positives and syntax-breaking autocorrects
Regression from new `RSpec/MetadataStyle` cop introduced in #1497.

### Reproduction example

Correct syntax as allowed by the rswag-specs gem:

```ruby
      response "404", "unauthorized access", api_docs: false do
        let(:authorization) { another_user.token }

        run_test!
      end
```

This probably triggers because we also have this in our Rubocop config:

```yaml
RSpec:
  Language:
    ExampleGroups:
      Regular:
        - response
```

False positive:

```
spec/requests/api/v0/foobar_spec.rb:30:23: C: [Correctable] RSpec/MetadataStyle: Use hash style for metadata.
      response "404", "unauthorized access", api_docs: false do
                      ^^^^^^^^^^^^^^^^^^^^^
```

Proposed auto-correct:

```ruby
      response "404", api_docs: false, unauthorized access: true do
        let(:authorization) { another_user.token }

        run_test!
      end
```

Notice how the "unauthorized access" string is treated like a symbol.

### Possible fix

Considering that the new cop supports the two styles "symbol" and "hash", it should probably just ignore strings? If you agree this is the right approach, I'm happy to attempt a fix.

### PR DESCRIPTION
**Pull request by franzliedke**
This fixes a false positive in an example group like the following:

```ruby
      response "404", "unauthorized access", api_docs: false do
        let(:authorization) { another_user.token }

        run_test!
      end
```

(This uses DSL from the `rswag` gem.)

Fixes #1714.

______________________________________________________________________

Before submitting the PR make sure the following are checked:

- [x] Feature branch is up-to-date with `master` (if not - rebase it).
- [x] Squashed related commits together.
- [x] Added tests.
- [ ] Updated documentation.
- [x] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
- [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

### CODE REVIEW

File: lib/rubocop/cop/rspec/mixin/metadata.rb [hunk 1]
```diff
@@ -46,7 +46,7 @@ def on_metadata(_symbols, _hash)
 
         private
 
-        def on_matadata_arguments(metadata_arguments)
+        def on_metadata_arguments(metadata_arguments)
```
Comment (franzliedke) [inline lib/rubocop/cop/rspec/mixin/metadata.rb:49]: Drive-by typo fix 😇

File: lib/rubocop/cop/rspec/metadata_style.rb [hunk 2]
```diff
@@ -45,6 +45,11 @@ class MetadataStyle < Base # rubocop:disable Metrics/ClassLength
         PATTERN
 
         def on_metadata(symbols, hash)
+          # RSpec example groups accept two string arguments. In such a case,
+          # the rspec_metadata matcher will interpret the second string
+          # argument as a metadata symbol.
+          symbols.shift if symbols.first&.str_type?
```
Comment (franzliedke) [inline lib/rubocop/cop/rspec/metadata_style.rb:51]: I first fixed this in the `rspec_metadata` matcher in `lib/rubocop/cop/rspec/mixin/metadata.rb` (see individual commits), but this made one test for the `RSpec/SortMetadata` cop fail. Looking at that cop, it seems to respect many more interesting cases, such as dynamic arguments, which could probably create more false positives in the `MetadataStyle` cop.

Example:

```ruby
context "something dynamic based on", variable do
  # ...
end
```

I decided not to dive into these cases and leave it to the AST matcher experts. (They may also be outside the scope of this PR, as this cop didn't worry about them so far.) Feel free to amend this PR if you see an obvious improvement.

**Comment by franzliedke** [comment]
This should fix the tests.

File: lib/rubocop/cop/rspec/metadata_style.rb (hunk 2 above)
Comment (bquorning) [reply lib/rubocop/cop/rspec/metadata_style.rb:51]: I suspect the real solution in mixin/metadata.rb would be to separate which metadata can be passed to `#Examples.all` vs `#ExampleGroups.all`, but I’m not sure I want to go down that rabbit hole 😅 The suggested fix works for me, too.

**Review by bquorning — APPROVED** [review]

**Comment by franzliedke** [comment]
@bquorning Thanks so much for the review, I appreciate it! Do I need to do something else (like squashing the commits), or just be patient? 😇

**Review by pirj — APPROVED** [review]
Thank you!
I had some ideas how to improve node patterns, but will attempt separately.

**Comment by bquorning** [comment]
> Do I need to do something else (like squashing the commits), or just be patient? 😇

Valid question 😅 If you squash the last 3 commits together, I’ll merge it.

**Comment by franzliedke** [comment]
@bquorning Consider it done. 👍🏼

**Review by bquorning — APPROVED** [review]
Thank you 👍🏼
