### PR TITLE
[Fix #1327] Fix a false positive for `RSpec/Capybara/SpecificMatcher`

### LINKED ISSUE #1327: [RSpec/Capybara/SpecificMatcher] Matching on attributes
AFAIK there's not a way to specify attributes with specific matchers:

`have_selector('a[data-disabled]', text: "Add Thing")`

This violates RSpec/Capybara/SpecificMatcher, but I don't think it's possible to express this with `have_link`, so  I think it's a false positive.

### PR DESCRIPTION
**Pull request by ydah**
Fix: #1327

---

Before submitting the PR make sure the following are checked:

* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [-] Updated documentation.
* [x] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
* [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

If you have created a new cop:

* [-] Added the new cop to `config/default.yml`.
* [-] The cop is configured as `Enabled: pending` in `config/default.yml`.
* [-] The cop is configured as `Enabled: true` in `.rubocop.yml`.
* [-] The cop documents examples of good and bad code.
* [-] The tests assert both that bad code is reported and that good code is not reported.
* [-] Set `VersionAdded` in `default/config.yml` to the next minor version.

If you have modified an existing cop's configuration options:

* [-] Set `VersionChanged` in `config/default.yml` to the next major version.

### CODE REVIEW

File: lib/rubocop/cop/rspec/capybara/specific_matcher.rb [hunk 1]
```diff
@@ -59,6 +84,28 @@ def acceptable_pattern?(arg)
             arg.match?(/\[.+=\w+\]/) || arg.match?(/[ >,+]/)
           end
 
+          def specific_matcher_option?(arg, matcher)
+            attribute = arg.slice(/\[[\w\W]*\]/)&.gsub!(/[\[\]]*/, '')
```
Comment (pirj) [inline lib/rubocop/cop/rspec/capybara/specific_matcher.rb:88]: Cosmetic: does it have to be a bang-`gsub`?
I'm too bad with regexp, do you mind adding a short note what this does exactly?

File: lib/rubocop/cop/rspec/capybara/specific_matcher.rb [hunk 2]
```diff
@@ -59,6 +84,28 @@ def acceptable_pattern?(arg)
...
+            if attribute
```
Comment (pirj) [inline lib/rubocop/cop/rspec/capybara/specific_matcher.rb:89]: Cosmetic suggestion:
```ruby
return true unless attribute

specific_matcher_options(matcher).include?(attribute)
```

File: spec/rubocop/cop/rspec/capybara/specific_matcher_spec.rb [hunk 3]
```diff
@@ -60,20 +60,72 @@
...
   end
 
   it 'does not register an offense for abstract matcher when ' \
     'first argument is element with nonreplaceable attributes' do
     expect_no_offenses(<<-RUBY)
-      expect(page).to have_css('button[foo=bar]')
-      expect(page).to have_css('button[foo-bar=baz]', exact_text: 'foo')
+    expect(page).to have_css('button[data_disabled]')
+    expect(page).to have_css('button[foo=bar]')
+    expect(page).to have_css('button[foo-bar=baz]', exact_text: 'foo')
```
Comment (pirj) [inline spec/rubocop/cop/rspec/capybara/specific_matcher_spec.rb:128]: Cosmetic: I really prefer it indented as above.

File: spec/rubocop/cop/rspec/capybara/specific_matcher_spec.rb [hunk 4]
```diff
@@ -60,20 +60,72 @@
...
   end
 
+  %i[above below left_of right_of near count minimum maximum between text id
+     class style visible obscured exact exact_text normalize_ws match wait
+     filter_set focused disabled name value title type name
+     disabled].each do |attr|
+    it 'registers an offense for abstract matcher when ' \
+      "first argument is button element with #{attr}" do
+      expect_offense(<<-RUBY, attr: attr)
+        expect(page).to have_css("button[#{attr}]")
```
Comment (pirj) [inline spec/rubocop/cop/rspec/capybara/specific_matcher_spec.rb:70]: I don't get it, do we check that we flag `have_css("button[with]")` as an offence? Is this a legitimate syntax?

File: lib/rubocop/cop/rspec/capybara/specific_matcher.rb [hunk 5]
```diff
@@ -28,6 +28,30 @@ class SpecificMatcher < Base
...
+          HAVE_BUTTON_OPTIONS = %w[above below left_of right_of near count
+                                   minimum maximum between text id class
+                                   style visible obscured exact exact_text
+                                   normalize_ws match wait filter_set focused
+                                   disabled name value title type name
+                                   disabled].freeze
+          HAVE_LINK_OPTIONS = %w[above below left_of right_of near count
+                                 minimum maximum between text id class style
+                                 visible obscured exact exact_text normalize_ws
+                                 match wait filter_set focused href href
```
Comment (pirj) [inline lib/rubocop/cop/rspec/capybara/specific_matcher.rb:40]: Double `href`.
What makes me wonder if there are other duplicates.

File: lib/rubocop/cop/rspec/capybara/specific_matcher.rb (hunk 1 above)
Comment (ydah) [reply lib/rubocop/cop/rspec/capybara/specific_matcher.rb]: It did not have to be bang-gsub. I have written a description of what I do at regex.

File: lib/rubocop/cop/rspec/capybara/specific_matcher.rb (hunk 2 above)
Comment (ydah) [reply lib/rubocop/cop/rspec/capybara/specific_matcher.rb]: It's certainly better that way. Fixed.

File: spec/rubocop/cop/rspec/capybara/specific_matcher_spec.rb (hunk 3 above)
Comment (ydah) [reply spec/rubocop/cop/rspec/capybara/specific_matcher_spec.rb]: Oops, fixed.

File: spec/rubocop/cop/rspec/capybara/specific_matcher_spec.rb (hunk 4 above)
Comment (ydah) [reply spec/rubocop/cop/rspec/capybara/specific_matcher_spec.rb:71]: This cop only offense attributes that can be replaced by specific matcher. I think the `it` explanation was confusing. Improved description. How do you like it?

File: lib/rubocop/cop/rspec/capybara/specific_matcher.rb (hunk 5 above)
Comment (ydah) [reply lib/rubocop/cop/rspec/capybara/specific_matcher.rb]: Oops, I reviewed the other definitions as well.

Comment (ydah) [reply lib/rubocop/cop/rspec/capybara/specific_matcher.rb]: I was referring to the capybara error message. but it appears to have been a duplicate suggestion display.
https://github.com/teamcapybara/capybara/pull/2572

**Comment by pirj** [comment]
I'm curious, should this be offensive or not?
```ruby
expect(page).to have_css("a[href=google.com]")
```
Specs currently tell it's not, but that
```ruby
expect(page).to have_css("a[href]")
```
is.

Same for e.g.
```ruby
expect(page).to have_css("button[name=click-me]")
```
vs
```ruby
expect(page).to have_css("button[name]")
```

Is it common to use `name`/`href` without a value in selectors?

**Comment by ydah** [comment]
Indeed it is. Thank you so much.

I've considered offense both of the following:

```ruby
expect(page).to have_css("a[href=google.com]")
expect(page).to have_css("a[href]")
```

How about this?

**Comment by pirj** [comment]
Nice!

> I've considered offense both of the following:
```ruby
expect(page).to have_css("a[href=google.com]")
expect(page).to have_css("a[href]")
```

I could only find the first one is specs.
```ruby
expect(page).to have_css("select[#{attr}=foo]")
```
Do you mind adding the second one, too? I can imaging e.g `visible` or `disabled` can be used without the value.
I suggest keeping them in the same examples, e.g.:
```ruby
        expect(page).to have_css("table[#{attr}=foo]")
                        ^^^^^^^^^^^^^^^^^{attr}^^^^^^^ Prefer `have_table` over `have_css`.
        expect(page).to have_css("table[#{attr}]")
                        ^^^^^^^^^^^^^^^^^{attr}^^^ Prefer `have_table` over `have_css`.
```

**Comment by ydah** [comment]
It certainly looks better that way. I've added a test.

**Review by pirj — APPROVED** [review]
Thank you!

File: lib/rubocop/cop/rspec/capybara/specific_matcher.rb [hunk 6]
```diff
@@ -56,7 +79,31 @@ def specific_matcher(arg)
           end
 
           def acceptable_pattern?(arg)
-            arg.match?(/\[.+=\w+\]/) || arg.match?(/[ >,+]/)
+            arg.match?(/[ >,+]/)
+          end
+
+          def specific_matcher_option?(arg, matcher)
+            # If `button[foo-bar_baz=foo]`, extract the "foo-bar_baz".
+            attribute = arg.slice(/\[[\w\W]*\]/)
```
Comment (bquorning) [inline lib/rubocop/cop/rspec/capybara/specific_matcher.rb:87]: Two questions:
1. Can there be more than one attribute within the brackets?
2. Would a regular expression (with capture) be easier to use here?

Comment (ydah) [reply lib/rubocop/cop/rspec/capybara/specific_matcher.rb]: > 1. Can there be more than one attribute within the brackets?

The following code will result in a syntax error.
```ruby
expect(page).to have_css("a[href="http://example.com" disabled]")
=> Failure/Error: expect(page).to have_css('a[href="http://example.com" disabled]')
     
     Nokogiri::CSS::SyntaxError:
       unexpected ' ' after '#<Nokogiri::CSS::Node:0x00007fddf305d998>'
     # (eval):3:in `_racc_do_parse_c'
     # (eval):3:in `do_parse'
     # ./spec/capybara/sandbox_spec.rb:8:in `block (2 levels) in <top (required)>'
```

However, multiple attributes can be specified as shown below, so I've added tests for multiple attributes.
```ruby
expect(page).to have_css('a[href="http://example.com"][disabled]')
```

Comment (ydah) [reply lib/rubocop/cop/rspec/capybara/specific_matcher.rb]: >2. Would a regular expression (with capture) be easier to use here?

Indeed it is. Thank you so much. I updated it.

File: lib/rubocop/cop/rspec/capybara/specific_matcher.rb [hunk 7]
```diff
@@ -56,7 +79,31 @@ def specific_matcher(arg)
...
+            arg.match?(/[ >,+]/)
+          end
+
+          def specific_matcher_option?(arg, matcher)
+            # If `button[foo-bar_baz=foo][bar][baz]`:
+            # extract "foo-bar_baz][bar][baz"
+            attributes, = arg.match(/\[([\w\W]*)\]/)&.captures
+            return true unless attributes
+
+            attributes.split('][').all? do |attr|
```
Comment (bquorning) [inline lib/rubocop/cop/rspec/capybara/specific_matcher.rb:91]: How about e.g.
```suggestion
            # If `button[foo-bar_baz=foo][bar][baz]`:
            # extract ["foo-bar_baz", "bar", "baz"]
            attributes = arg.scan(/\[(.*?)\]/).flatten
            return true if attributes.empty?

            attributes.all? do |attr|
```

Comment (ydah) [reply lib/rubocop/cop/rspec/capybara/specific_matcher.rb]: I was having a little trouble there, but it looks to have improved  and better way to me. Thank you so much.

**Review by bquorning — APPROVED** [review]

File: lib/rubocop/cop/rspec/capybara/specific_matcher.rb [hunk 8]
```diff
@@ -28,6 +28,28 @@ class SpecificMatcher < Base
           MSG = 'Prefer `%<good_matcher>s` over `%<bad_matcher>s`.'
           RESTRICT_ON_SEND = %i[have_selector have_no_selector have_css
                                 have_no_css].freeze
+          HAVE_BUTTON_OPTIONS = %w[
```
Comment (Darhazer) [inline lib/rubocop/cop/rspec/capybara/specific_matcher.rb:31]: Perhaps we can extract `COMMON_OPTIONS` and then extend for the different elements

File: lib/rubocop/cop/rspec/capybara/specific_matcher.rb [hunk 9]
```diff
@@ -56,7 +79,31 @@ def specific_matcher(arg)
...
+          def specific_matcher_options(matcher)
+            case matcher
+            when 'button'
+              HAVE_BUTTON_OPTIONS
+            when 'link'
+              HAVE_LINK_OPTIONS
+            when 'table'
+              HAVE_TABLE_OPTIONS
+            when 'select'
+              HAVE_SELECT_OPTIONS
```
Comment (Darhazer) [inline lib/rubocop/cop/rspec/capybara/specific_matcher.rb:105]: should we default to [] if the matcher is not in the list (even though some other part might guarantee it's one of those)

File: lib/rubocop/cop/rspec/capybara/specific_matcher.rb [hunk 10]
```diff
@@ -56,7 +79,31 @@ def specific_matcher(arg)
...
 
           def acceptable_pattern?(arg)
-            arg.match?(/\[.+=\w+\]/) || arg.match?(/[ >,+]/)
+            arg.match?(/[ >,+]/)
+          end
+
+          def specific_matcher_option?(arg, matcher)
+            # If `button[foo-bar_baz=foo][bar][baz]`:
+            # extract ["foo-bar_baz", "bar", "baz"]
+            attributes = arg.scan(/\[(.*?)\]/).flatten
```
Comment (bquorning) [inline lib/rubocop/cop/rspec/capybara/specific_matcher.rb:88]: If we want to go all in on regex:
```suggestion
            attributes = arg.scan(/\[(.*?)(?:=.*?)?\]/).flatten
```
Then we can delete the `.split('=').first` in line 92.

File: lib/rubocop/cop/rspec/capybara/specific_matcher.rb (hunk 8 above)
Comment (ydah) [reply lib/rubocop/cop/rspec/capybara/specific_matcher.rb]: It certainly looks better that way. Thank you very much.

File: lib/rubocop/cop/rspec/capybara/specific_matcher.rb (hunk 9 above)
Comment (ydah) [reply lib/rubocop/cop/rspec/capybara/specific_matcher.rb]: I added this because it is an unlikely handling, but it certainly seemed like it would be better to have.

File: lib/rubocop/cop/rspec/capybara/specific_matcher.rb (hunk 10 above)
Comment (ydah) [reply lib/rubocop/cop/rspec/capybara/specific_matcher.rb]: It is clearly better that way. Thank you so much.

File: spec/rubocop/cop/rspec/capybara/specific_matcher_spec.rb [hunk 11]
```diff
@@ -21,62 +21,148 @@
...
+                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Prefer `have_button` over `have_css`.
+      expect(page).to have_css('button:not([disabled])', exact_text: 'bar')
+                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Prefer `have_button` over `have_css`.
     RUBY
   end
 
   it 'does not register an offense for abstract matcher when ' \
     'first argument is element with nonreplaceable attributes' do
     expect_no_offenses(<<-RUBY)
+      expect(page).to have_css('button[data_disabled]')
```
Comment (Darhazer) [inline spec/rubocop/cop/rspec/capybara/specific_matcher_spec.rb:149]: `[data-disabled]` is more realistic usage

**Review by Darhazer — APPROVED** [review]

**Review by bquorning — APPROVED** [review]

File: spec/rubocop/cop/rspec/capybara/specific_matcher_spec.rb (hunk 11 above)
Comment (ydah) [reply spec/rubocop/cop/rspec/capybara/specific_matcher_spec.rb]: Indeed it is. I change to `[data-disabled]`

**Review by bquorning — APPROVED** [review]

File: lib/rubocop/cop/rspec/capybara/specific_matcher.rb [hunk 12]
```diff
@@ -28,6 +28,24 @@ class SpecificMatcher < Base
...
           RESTRICT_ON_SEND = %i[have_selector have_no_selector have_css
                                 have_no_css].freeze
+          COMMON_OPTIONS = %w[
+            above below left_of right_of near count minimum maximum between text
+            id class style visible obscured exact exact_text normalize_ws match
+            wait filter_set focused
+          ].freeze
+          HAVE_BUTTON_OPTIONS = COMMON_OPTIONS + %w[
+            disabled name value title type
+          ].freeze
```
Comment (bquorning) [inline lib/rubocop/cop/rspec/capybara/specific_matcher.rb:38]: I just realized that this way, `HAVE_BUTTON_OPTIONS` is not frozen. We’d have to do e.g.
```rb
HAVE_BUTTON_OPTIONS = (COMMON_OPTIONS + %w[
  disabled name value title type
]).freeze
```
which really doesn’t seem very elegant.

Perhaps we should just have one big SPECIFIC_MATCHER_OPTIONS hash instead? What do you think @ydah?

```rb
SPECIFIC_MATCHER_OPTIONS = {
  'button' => COMMON_OPTIONS + %w[
    disabled name value title type
  ],
  'link' => COMMON_OPTIONS + %w[
    href alt title download
  ],
  'table' => COMMON_OPTIONS + %w[
    caption with_cols cols with_rows rows
  ],
  'select' => COMMON_OPTIONS + %w[
    disabled name placeholder options enabled_options disabled_options
    selected with_selected multiple with_options
  ]
}.freeze
```

Comment (BrianHawley) [reply lib/rubocop/cop/rspec/capybara/specific_matcher.rb:38]: You'd still have to freeze the hash values, but that can be done like this:
```ruby
SPECIFIC_MATCHER_OPTIONS = {
  #...
}.each_value(&:freeze).freeze
```

Comment (bquorning) [reply lib/rubocop/cop/rspec/capybara/specific_matcher.rb:38]: In that case, I think I’d prefer calling `freeze` directly on the created arrays anyway:
```rb
SPECIFIC_MATCHER_OPTIONS = {
  'button' => (
    COMMON_OPTIONS + %w[disabled name value title type]
  ).freeze,
  'link' => (
    COMMON_OPTIONS + %w[href alt title download]
  ).freeze,
  'table' => (
    COMMON_OPTIONS + %w[caption with_cols cols with_rows rows]
  ).freeze,
  'select' => (
    COMMON_OPTIONS + %w[
      disabled name placeholder options enabled_options
      disabled_options selected with_selected multiple with_options
    ]
  ).freeze
}.freeze
```

Comment (pirj) [reply lib/rubocop/cop/rspec/capybara/specific_matcher.rb:38]: My apologies for merging this. I've just realized there are more comments added after I last refreshed the page.
I hope it's not something that can't be fixed in a follow-up.

**Comment by pirj** [comment]
Thank you for the fix, @ydah !
