### PR TITLE
Fix false negative in `RSpec/ExpectChange` cop with block style and chained method call

### LINKED ISSUE #1143: False negative in RSpec/ExpectChange with block style
Given:
```yml
RSpec/ExpectChange:
  EnforcedStyle: block
```
the cop is missing the following:
```ruby
      expect { paint_users! }
        .to change(users.green, :count).by(1)
        .and change(PaintedAdmins.where('color ilike ?', color), :count).by(0)
```

### PR DESCRIPTION
**Pull request by tejasbubane**
Closes #1143

---

Before submitting the PR make sure the following are checked:

* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [ ] Updated documentation.
* [x] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
* [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

If you have created a new cop:

* [ ] Added the new cop to `config/default.yml`.
* [ ] The cop is configured as `Enabled: pending` in `config/default.yml`.
* [ ] The cop documents examples of good and bad code.
* [ ] The tests assert both that bad code is reported and that good code is not reported.
* [ ] Set `VersionAdded` in `default/config.yml` to the next minor version.

If you have modified an existing cop's configuration options:

* [ ] Set `VersionChanged` in `config/default.yml` to the next major version.

### CODE REVIEW

**Comment by tejasbubane** [comment]
Rubocop failures are unrelated and shall be fixed in https://github.com/rubocop/rubocop-rspec/pull/1154

**Review by pirj — APPROVED** [review]
Perfect, thank you!

**Review by pirj — APPROVED** [review]
```
Conflicting files
CHANGELOG.md
```
Prevents from merging :shrug:

**Review by pirj — APPROVED** [review]
Thanks!

File: lib/rubocop/cop/rspec/expect_change.rb [hunk 1]
```diff
@@ -39,7 +39,7 @@ class ExpectChange < Base
 
         # @!method expect_change_with_arguments(node)
         def_node_matcher :expect_change_with_arguments, <<-PATTERN
-          (send nil? :change ({const send} nil? $_) (sym $_))
+          (send nil? :change $({const send} ...) (sym $_))
```
Comment (Darhazer) [inline lib/rubocop/cop/rspec/expect_change.rb:42]: Do we need to limit the argument of change at all?
Could be just `(send nil? :change $_ (sym $_))`

**Review by Darhazer — APPROVED** [review]

File: lib/rubocop/cop/rspec/expect_change.rb (hunk 1 above)
Comment (pirj) [reply lib/rubocop/cop/rspec/expect_change.rb:42]: This way it would also match `change(@ivar, :method)`, `change($global, :method)`, `change(::Const, :count)` and other possible arguments.
I don't have a definitive list in my head, can there be any false positives? Something like `change(-> {}, :call)`?
👍 for such a change granted a few more examples are added.
@tejasbubane Are you up for that, or would you prefer us to file a ticket for the future?

Comment (pirj) [reply lib/rubocop/cop/rspec/expect_change.rb:42]: Wondering if `${const send}` can be a drop-in replacement for`$({const send} ...)` 🤔

Comment (tejasbubane) [reply lib/rubocop/cop/rspec/expect_change.rb]: Changed as per @Darhazer suggestion.

**Comment by tejasbubane** [comment]
@pirj I have enabled it now

**Comment by pirj** [comment]
```
﻿From 7df5b048523b257ac5e77c1204238e040daaf4f9 Mon Sep 17 00:00:00 2001
From: Phil Pirozhkov <pirjsuka@gmail.com>
Date: Tue, 25 May 2021 20:43:21 +0300
Subject: [PATCH] Add more specs for RSpec/ExpectChange

---
 spec/rubocop/cop/rspec/expect_change_spec.rb | 62 +++++++++++++++++++-
 1 file changed, 61 insertions(+), 1 deletion(-)

diff --git a/spec/rubocop/cop/rspec/expect_change_spec.rb b/spec/rubocop/cop/rspec/expect_change_spec.rb
index c0e7c726..95b7a547 100644
--- a/spec/rubocop/cop/rspec/expect_change_spec.rb
+++ b/spec/rubocop/cop/rspec/expect_change_spec.rb
@@ -67,7 +67,7 @@ RSpec.describe RuboCop::Cop::RSpec::ExpectChange do
       RUBY
     end
 
-    it 'flags change matcher when receiver is a variable' do
+    it 'flags change matcher when receiver is a constant' do
       expect_offense(<<-RUBY)
         it do
           expect { run }.to change(User, :count)
@@ -82,6 +82,36 @@ RSpec.describe RuboCop::Cop::RSpec::ExpectChange do
       RUBY
     end
 
+    it 'flags change matcher when receiver is a top-level constant' do
+      expect_offense(<<-RUBY)
+        it do
+          expect { run }.to change(::User, :count)
+                            ^^^^^^^^^^^^^^^^^^^^^^ Prefer `change { ::User.count }`.
+        end
+      RUBY
+
+      expect_correction(<<-RUBY)
+        it do
+          expect { run }.to change { ::User.count }
+        end
+      RUBY
+    end
+
+    it 'flags change matcher when receiver is a variable' do
+      expect_offense(<<-RUBY)
+        it do
+          expect { run }.to change(user, :status)
+                            ^^^^^^^^^^^^^^^^^^^^^ Prefer `change { user.status }`.
+        end
+      RUBY
+
+      expect_correction(<<-RUBY)
+        it do
+          expect { run }.to change { user.status }
+        end
+      RUBY
+    end
+
     it 'registers an offense for change matcher with chained method call' do
       expect_offense(<<-RUBY)
         it do
@@ -97,6 +127,36 @@ RSpec.describe RuboCop::Cop::RSpec::ExpectChange do
       RUBY
     end
 
+    it 'registers an offense for change matcher with an instance variable' do
+      expect_offense(<<-RUBY)
+        it do
+          expect { paint_users! }.to change(@food, :taste).to(:sour)
+                                     ^^^^^^^^^^^^^^^^^^^^^ Prefer `change { @food.taste }`.
+        end
+      RUBY
+
+      expect_correction(<<-RUBY)
+        it do
+          expect { paint_users! }.to change { @food.taste }.to(:sour)
+        end
+      RUBY
+    end
+
+    it 'registers an offense for change matcher with a global variable' do
+      expect_offense(<<-RUBY)
+        it do
+          expect { paint_users! }.to change($token, :value).to(nil)
+                                     ^^^^^^^^^^^^^^^^^^^^^^ Prefer `change { $token.value }`.
+        end
+      RUBY
+
+      expect_correction(<<-RUBY)
+        it do
+          expect { paint_users! }.to change { $token.value }.to(nil)
+        end
+      RUBY
+    end
+
     it 'ignores methods called change' do
       expect_no_offenses(<<-RUBY)
         it do
-- 
2.29.2
```

File: lib/rubocop/cop/rspec/expect_change.rb (hunk 1 above)
Comment (pirj) [reply lib/rubocop/cop/rspec/expect_change.rb]: @bquorning What do you think?

**Comment by pirj** [comment]
Thank you!

**Comment by Darhazer** [comment]
Thank you for expanding the test suite :bow:
