### PR TITLE
Fix EmptyMetadata for splat kwargs

### LINKED ISSUE #2004: RSpec/EmptyMetadata false positive with double splat
Using the double splat to pass metadata to an example causes a false positive when `RSpec/EmptyMetadata` is enabled.
______________________________________________________________________

## Expected behavior

Given the following spec:

```ruby
Spec.describe Client do 
  subject(:client) { described_class.new }

  def self.vcr(name)
    { vcr: { cassette_name: "client/#{name}" } } 
  end
    
  describe '#get' do
    it 'returns a value', **vcr('get') do
      expect(client.get).to_not be_nil
    end
  end
end
```

No Rubocop failures should be reported.

## Actual behavior

```
For /app: configuration from /app/.rubocop.yml
configuration from /app/.bundle/ruby/3.3.0/gems/rubocop-rails-2.25.1/config/default.yml
configuration from /app/.bundle/ruby/3.3.0/gems/rubocop-rails-2.25.1/config/default.yml
Default configuration from /app/.bundle/ruby/3.3.0/gems/rubocop-1.65.0/config/default.yml
configuration from /app/.bundle/ruby/3.3.0/gems/rubocop-rspec-3.0.3/config/default.yml
configuration from /app/.bundle/ruby/3.3.0/gems/rubocop-rspec-3.0.3/config/default.yml
configuration from /app/.bundle/ruby/3.3.0/gems/rubocop-capybara-2.21.0/config/default.yml
configuration from /app/.bundle/ruby/3.3.0/gems/rubocop-capybara-2.21.0/lib/../config/default.yml
Use parallel by default.
Skipping parallel inspection: only a single file needs inspection
Inspecting 1 file
Scanning /app/spec/client_spec.rb
Loading cache from ~/.cache/rubocop_cache/63cf0958ae1ffa47b1ecc6e5b14c8ab2bfaf29bf/21324dd8cc78aa590578594baefc69b44b97dca2/b343790ba7067ea328187c982c280b3a76448e97
C

Offenses:

spec/client_spec.rb:9:27: C: [Correctable] RSpec/EmptyMetadata: Avoid empty metadata hash.
    it 'returns a value', **vcr('get') do
                          ^^^^^^^^^^^^

1 file inspected, 1 offense detected, 1 offense autocorrectable
Finished in 0.23803600016981363 seconds
```

## Steps to reproduce the problem

Use double splat to destructure metadata passed to example.

## RuboCop RSpec version

```shell
$ rubocop -V
1.65.0 (using Parser 3.3.4.0, rubocop-ast 1.31.3, running on ruby 3.3.4) [arm64-darwin23]
  - rubocop-capybara 2.21.0
  - rubocop-rails 2.25.1
  - rubocop-rspec 3.0.3
```

### PR DESCRIPTION
**Pull request by pirj**
Fixes #2004, when metadata is detected as empty when it's actually a kwargs splat.

cc @tylerhunt
______________________________________________________________________

Before submitting the PR make sure the following are checked:

- [x] Feature branch is up-to-date with `master` (if not - rebase it).
- [x] Squashed related commits together.
- [x] Added tests.
- [-] Updated documentation.
- [x] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
- [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

### CODE REVIEW

File: lib/rubocop/cop/rspec/empty_metadata.rb [hunk 1]
```diff
@@ -21,6 +21,7 @@ class EmptyMetadata < Base
 
         def on_metadata(_symbols, hash)
           return unless hash&.pairs&.empty?
+          return if hash.children.any?(&:kwsplat_type?)
```
Comment (pirj) [inline lib/rubocop/cop/rspec/empty_metadata.rb:24]: https://github.com/rubocop/rubocop-ast/blob/944ced4fa09f431668d1b22e0ce37fd94c280489/spec/rubocop/ast/keyword_splat_node_spec.rb#L31

**Comment by tylerhunt** [comment]
Thanks, @pirj!

**Review by bquorning — APPROVED** [review]
