### PR TITLE
Fix error in `RSpec/RSpec/FactoryBot/CreateList` cop for empty block

### LINKED ISSUE #1284: `RSpec/FactoryBot/CreateList` fails to parse `10.times {}`
Using Rubocop 1.30.0 (using Parser 3.1.2.0, rubocop-ast 1.18.0, running on ruby 2.7.5 x86_64-darwin20)

Given a file with the following code:
```ruby
# rubocop:disable all
# rubocop:enable RSpec/FactoryBot/CreateList
10.times {}
```

We see the following error:
```
An error occurred while RSpec/FactoryBot/CreateList cop was inspecting /Users/hosamaly/monorepo/commons-ruby/boardintelligence-rails/x_spec.rb:3:0.
  undefined method `block_type?' for nil:NilClass
rubocop-rspec-2.10.0/lib/rubocop/cop/rspec/factory_bot/create_list.rb:79:in `contains_only_factory?'
rubocop-rspec-2.10.0/lib/rubocop/cop/rspec/factory_bot/create_list.rb:58:in `on_block'
rubocop-1.30.0/lib/rubocop/cop/commissioner.rb:100:in `public_send'
rubocop-1.30.0/lib/rubocop/cop/commissioner.rb:100:in `block (2 levels) in trigger_responding_cops'
rubocop-1.30.0/lib/rubocop/cop/commissioner.rb:160:in `with_cop_error_handling'
rubocop-1.30.0/lib/rubocop/cop/commissioner.rb:99:in `block in trigger_responding_cops'
rubocop-1.30.0/lib/rubocop/cop/commissioner.rb:98:in `each'
rubocop-1.30.0/lib/rubocop/cop/commissioner.rb:98:in `trigger_responding_cops'
rubocop-1.30.0/lib/rubocop/cop/commissioner.rb:69:in `on_block'
rubocop-ast-1.18.0/lib/rubocop/ast/traversal.rb:20:in `walk'
...
```

### PR DESCRIPTION
**Pull request by tejasbubane**
Closes #1284

---

Before submitting the PR make sure the following are checked:

* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [ ] Updated documentation.
* [x] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
* [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

### CODE REVIEW

File: lib/rubocop/cop/rspec/factory_bot/create_list.rb [hunk 1]
```diff
@@ -76,7 +76,7 @@ def on_send(node)
           private
 
           def contains_only_factory?(node)
-            if node.block_type?
+            if node&.block_type?
```
Comment (pirj) [inline lib/rubocop/cop/rspec/factory_bot/create_list.rb:79]: WDYT of adding after line 57?
```ruby
return unless node.body
```

**Review by pirj — APPROVED** [review]
Thanks for such a quick fix, @tejasbubane !
