### PR TITLE
[Fix #1237] Fix `Capybara/CurrentPathExpectation` autocorrect incompatible with `Style/TrailingCommaInArguments` autocorrect

### LINKED ISSUE #1237: Capybara/CurrentPathException autocorrect incompatible with Style/TrailingComma autocorrect
rubocop version: 1.18.3
rubocop-rspec version: 2.4.0

Example code:

```ruby
# original code
expect(current_path).to eq(
  some_path(
    record_id: record.id
  )
)
```

If Style/TrailingComma (in vanilla rubocop) is enabled for methods, it adds a comma after `record.id` and after the closed parenthesis.

Also, Capybara/CurrentPathExpectation adds `, ignore_query: true` to the `have_current_path` params. If both are fixed with the same autocorrect, the following is the result:

```ruby
# after autocorrect
expect(page).to have_current_path(
  some_path(
    record_id: record.id
  ),, ignore_query: true
)
```

which is a syntax error (the double-comma) and still doesn't have the trailing comma.

A workaround is to run the Style cops first, then the RSpec cops, or vice-versa - just not in the same command

### PR DESCRIPTION
**Pull request by ydah**
I accidentally Close: https://github.com/rubocop/rubocop-rspec/pull/1252 Sorry.

Fixes https://github.com/rubocop/rubocop-rspec/issues/1237

This PR fixes `Capybara/CurrentPathExpectation` autocorrect incompatible with `Style/TrailingCommaInArguments` autocorrect when code like the following:

```ruby
expect(current_path).to eq(
  some_path(
    record_id: record.id
  )
)
```

---

Before submitting the PR make sure the following are checked:

* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [ ] Updated documentation.
* [x] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
* [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

### CODE REVIEW

File: lib/rubocop-rspec.rb [hunk 1]
```diff
@@ -37,16 +37,36 @@
...
+        end
+
+        def autocorrect_incompatible_with_extend(*args)
+          TrailingCommaInArguments.autocorrect_incompatible_with_extend(*args)
+        end
+
+        class << self
+          alias autocorrect_incompatible_with_org autocorrect_incompatible_with
+          alias autocorrect_incompatible_with autocorrect_incompatible_with_ext
+        end
```
Comment (bquorning) [inline lib/rubocop-rspec.rb:65]: Instead of an alias-method chain, we could do module-prepending which I think is cleaner:
```rb
RuboCop::Cop::Layout::ExtraSpacing.singleton_class.prepend(Module.new do
  def autocorrect_incompatible_with
    [RSpec::AlignLeftLetBrace, RSpec::AlignRightLetBrace]
  end
end)

RuboCop::Cop::Style::TrailingCommaInArguments.singleton_class.prepend(Module.new do
  def autocorrect_incompatible_with
    [RSpec::Capybara::CurrentPathExpectation]
  end
end)
```

Of course this is very much repetitive, so perhaps later we should consider adding a class method to `Cop` that can add all this code with a single call. But definitely not for this PR though.

Comment (Darhazer) [reply lib/rubocop-rspec.rb:65]: IMO it should be `append` and concating to the `super`, otherwise it will still be just replaced by the original code

Comment (bquorning) [reply lib/rubocop-rspec.rb:65]: 🤦🏼 Of course, I’m not sure how I managed to write down only half of my thoughts before commenting. Thanks for catching that @Darhazer. What I meant was something along the lines of
```rb
RuboCop::Cop::Layout::ExtraSpacing.singleton_class.prepend(Module.new do
  def autocorrect_incompatible_with
    super.push(RSpec::AlignLeftLetBrace).push(RSpec::AlignRightLetBrace)
  end
end)

RuboCop::Cop::Style::TrailingCommaInArguments.singleton_class.prepend(Module.new do
  def autocorrect_incompatible_with
    super.push(RSpec::Capybara::CurrentPathExpectation)
  end
end)

Comment (ydah) [reply lib/rubocop-rspec.rb]: Thanks. I'll use module-prepending, as it certainly feels cleaner that way.

**Comment by ydah** [comment]
I updated this PR. Thank you so much!

**Review by Darhazer — APPROVED** [review]
