### PR TITLE
Fix a false positive for RSpec/ExpectActual with rspec-rails

### LINKED ISSUE #759: RSpec/ExpectActual false positive against routing specs (when using a negated matcher)
On our project we have a test as follows:
```ruby
expect(get: :show, params: { id: 'null', format: :json }).not_to be_routable
```

Which is in turn raising a cop:
```ruby
C: RSpec/ExpectActual: Provide the actual you are testing to expect(...).
          expect(get: :show, params: { id: 'null', format: :json }).not_to be_routable
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I understand that this is very similar to #198. Our `route_to` tests work fine though.

Useful info:
```
$ bundle exec rubocop -v
0.64.0
$ bundle exec rails -v
Rails 5.2.3
$ ruby -v
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin17]
```

### PR DESCRIPTION
**Pull request by naveg**
rspec-rails comes with routing matchers that use literals in the `expect()`.

Fixes #759

______________________________________________________________________

Before submitting the PR make sure the following are checked:

- [x] Feature branch is up-to-date with `master` (if not - rebase it).
- [x] Squashed related commits together.
- [x] Added tests.
- [x] Updated documentation.
- [x] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
- [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

If you have created a new cop:

- [ ] Added the new cop to `config/default.yml`.
- [ ] The cop is configured as `Enabled: pending` in `config/default.yml`.
- [ ] The cop is configured as `Enabled: true` in `.rubocop.yml`.
- [ ] The cop documents examples of good and bad code.
- [ ] The tests assert both that bad code is reported and that good code is not reported.
- [ ] Set `VersionAdded: "<<next>>"` in `default/config.yml`.

If you have modified an existing cop's configuration options:

- [ ] Set `VersionChanged: "<<next>>"` in `config/default.yml`.

### CODE REVIEW

**Review by pirj — APPROVED** [review]
Perfect, thank you!

File: lib/rubocop/cop/rspec/expect_actual.rb [hunk 1]
```diff
@@ -66,6 +67,8 @@ class ExpectActual < Base
 
         def on_send(node)
           expect_literal(node) do |actual, matcher, expected|
+            next if SKIPPED_MATCHERS.include?(matcher)
+
             add_offense(actual.source_range) do |corrector|
               next unless SUPPORTED_MATCHERS.include?(matcher)
```
Comment (bquorning) [inline lib/rubocop/cop/rspec/expect_actual.rb:73]: I was a bit confused that we’d need both “skipped matchers” and “supported matchers”. Perhaps the supported matchers should be renamed “correctable matchers”? 😅

File: lib/rubocop/cop/rspec/expect_actual.rb [hunk 2]
```diff
@@ -50,6 +50,7 @@ class ExpectActual < Base
           regexp
         ].freeze
 
+        SKIPPED_MATCHERS = %i[route_to be_routable].freeze
```
Comment (bquorning) [inline lib/rubocop/cop/rspec/expect_actual.rb:53]: Since we are planning to extract the rspec-rails specific parts from rubocop-rspec, I don’t think we should hardcode these matchers names. Can we either have (the non-existing) rubocop-rspec-rails inject them, or maybe just add a `SkippedMatchers` to the configuration?

Comment (naveg) [reply lib/rubocop/cop/rspec/expect_actual.rb:53]: Could we wait to see how the rails extraction takes shape before doing that? It's true that this is rails-specific, but it's also highly unlikely to matter, since we'd only miss adding offenses for non-rails matchers that happened to be named "route_to" or "be_routable".

**Review by bquorning — APPROVED** [review]

File: CHANGELOG.md [hunk 3]
```diff
@@ -5,6 +5,7 @@
 ## 2.26.1 (2024-01-05)
 
 - Fix an error for `RSpec/SharedExamples` when using examples without argument. ([@ydah])
+- Fix a false positive for `RSpec/ExpectActual` when used with rspec-rails routing matchers. ([@naveg])
```
Comment (bquorning) [inline CHANGELOG.md:8]: Please move this line to the `Unreleased` section :-)

Comment (naveg) [reply CHANGELOG.md]: woops, fixed
