### PR TITLE
Fix an invalid autocorrect for RSpec/MatchArray

### LINKED ISSUE #1591: RSpec/MatchArray autocorrects empty array to nil
## Expected behavior

When using Rubocops autocorrect behavior on the RSpec/MatchArray cop, autocorrections of matching on an empty array should change to contain_exactly an empty array.

## Actual behavior

It changes `match_array([])` to `match_array` and then causes errors when running subsequent rubocop checks on the file.

```
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-rspec-2.19.0/lib/rubocop/cop/rspec/match_array.rb:27:in `on_send'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:143:in `public_send'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:143:in `block (2 levels) in trigger_restricted_cops'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:171:in `with_cop_error_handling'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:142:in `block in trigger_restricted_cops'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:141:in `each'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:141:in `trigger_restricted_cops'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:70:in `on_send'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:159:in `block in on_send'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:156:in `each'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:156:in `each_with_index'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:156:in `on_send'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:71:in `on_send'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:158:in `on_block'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:71:in `on_block'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:137:in `block in on_dstr'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:137:in `each'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:137:in `on_dstr'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:71:in `on_begin'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:158:in `on_block'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:71:in `on_block'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:137:in `block in on_dstr'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:137:in `each'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:137:in `on_dstr'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:71:in `on_begin'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:158:in `on_block'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:71:in `on_block'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:137:in `block in on_dstr'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:137:in `each'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:137:in `on_dstr'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:71:in `on_begin'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:20:in `walk'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:87:in `investigate'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/team.rb:156:in `investigate_partial'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/team.rb:98:in `investigate'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:345:in `block in inspect_file'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:344:in `each'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:344:in `flat_map'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:344:in `inspect_file'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:287:in `block in do_inspection_loop'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:321:in `block in iterate_until_no_changes'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:314:in `loop'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:314:in `iterate_until_no_changes'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:283:in `do_inspection_loop'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:164:in `block in file_offenses'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:189:in `file_offense_cache'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:163:in `file_offenses'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:154:in `process_file'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:135:in `block in each_inspected_file'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:134:in `each'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:134:in `reduce'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:134:in `each_inspected_file'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:120:in `inspect_files'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:73:in `run'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli/command.rb:11:in `run'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli/environment.rb:18:in `run'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli.rb:118:in `run_command'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli.rb:125:in `execute_runners'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli.rb:51:in `block in run'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli.rb:77:in `profile_if_needed'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli.rb:43:in `run'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/exe/rubocop:19:in `block in <top (required)>'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/3.1.0/benchmark.rb:311:in `realtime'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/exe/rubocop:19:in `<top (required)>'
/Users/kyle/.rbenv/versions/3.1.3/bin/rubocop:25:in `load'
/Users/kyle/.rbenv/versions/3.1.3/bin/rubocop:25:in `<main>'
An error occurred while RSpec/MatchArray cop was inspecting /Users/kyle/code/marketplace/spec/repositories/payment_message_terms_repository_spec.rb:103:84.
undefined method `array_type?' for nil:NilClass

          return unless node.first_argument.array_type?
                                           ^^^^^^^^^^^^
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-rspec-2.19.0/lib/rubocop/cop/rspec/match_array.rb:27:in `on_send'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:143:in `public_send'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:143:in `block (2 levels) in trigger_restricted_cops'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:171:in `with_cop_error_handling'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:142:in `block in trigger_restricted_cops'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:141:in `each'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:141:in `trigger_restricted_cops'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:70:in `on_send'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:159:in `block in on_send'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:156:in `each'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:156:in `each_with_index'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:156:in `on_send'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:71:in `on_send'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:158:in `on_block'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:71:in `on_block'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:137:in `block in on_dstr'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:137:in `each'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:137:in `on_dstr'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:71:in `on_begin'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:158:in `on_block'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:71:in `on_block'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:137:in `block in on_dstr'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:137:in `each'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:137:in `on_dstr'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:71:in `on_begin'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:158:in `on_block'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:71:in `on_block'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:137:in `block in on_dstr'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:137:in `each'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:137:in `on_dstr'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:71:in `on_begin'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:20:in `walk'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:87:in `investigate'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/team.rb:156:in `investigate_partial'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/team.rb:98:in `investigate'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:345:in `block in inspect_file'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:344:in `each'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:344:in `flat_map'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:344:in `inspect_file'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:287:in `block in do_inspection_loop'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:321:in `block in iterate_until_no_changes'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:314:in `loop'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:314:in `iterate_until_no_changes'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:283:in `do_inspection_loop'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:164:in `block in file_offenses'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:189:in `file_offense_cache'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:163:in `file_offenses'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:154:in `process_file'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:135:in `block in each_inspected_file'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:134:in `each'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:134:in `reduce'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:134:in `each_inspected_file'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:120:in `inspect_files'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:73:in `run'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli/command.rb:11:in `run'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli/environment.rb:18:in `run'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli.rb:118:in `run_command'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli.rb:125:in `execute_runners'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli.rb:51:in `block in run'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli.rb:77:in `profile_if_needed'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli.rb:43:in `run'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/exe/rubocop:19:in `block in <top (required)>'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/3.1.0/benchmark.rb:311:in `realtime'
/Users/kyle/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/exe/rubocop:19:in `<top (required)>'
/Users/kyle/.rbenv/versions/3.1.3/bin/rubocop:25:in `load'
/Users/kyle/.rbenv/versions/3.1.3/bin/rubocop:25:in `<main>'
.

1 file inspected, no offenses detected

5 errors occurred:
An error occurred while RSpec/MatchArray cop was inspecting /Users/kyle/code/marketplace/spec/repositories/payment_message_terms_repository_spec.rb:47:68.
An error occurred while RSpec/MatchArray cop was inspecting /Users/kyle/code/marketplace/spec/repositories/payment_message_terms_repository_spec.rb:55:71.
An error occurred while RSpec/MatchArray cop was inspecting /Users/kyle/code/marketplace/spec/repositories/payment_message_terms_repository_spec.rb:95:99.
An error occurred while RSpec/MatchArray cop was inspecting /Users/kyle/code/marketplace/spec/repositories/payment_message_terms_repository_spec.rb:99:98.
An error occurred while RSpec/MatchArray cop was inspecting /Users/kyle/code/marketplace/spec/repositories/payment_message_terms_repository_spec.rb:103:84.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
https://github.com/rubocop/rubocop/issues

Mention the following information in the issue report:
1.48.0 (using Parser 3.2.1.0, rubocop-ast 1.27.0, running on ruby 3.1.3) [x86_64-darwin21]
Finished in 1.0074199999216944 seconds
```
Screen Shot 2023-03-07 at 11 47 55 AM

## Steps to reproduce the problem
running `rubocop --autocorrect --only RSpec/MatchArray` on specs with matches on an empty array.

## RuboCop version

```
1.48.0 (using Parser 3.2.1.0, rubocop-ast 1.27.0, running on ruby 3.1.3) [x86_64-darwin21]
  - rubocop-performance 1.16.0
  - rubocop-rails 2.18.0
  - rubocop-rspec 2.19.0
```

### LINKED ISSUE #1595: RSpec/MatchArray: Incorrect correction applied, causes failure in inspection
When running `bundle exec rubocop -a` I encountered an issue with the MatchArray cop.

The following correction is offered:
```
spec.rb:32:32: C: [Correctable] RSpec/MatchArray: Prefer contain_exactly when matching an array literal.
        expect(action.call).to match_array([])
                               ^^^^^^^^^^^^^^^
```

And this is what was applied:
```diff
       it "returns an empty array" do
-        expect(action.call).to match_array([])
+        expect(action.call).to match_array
       end
```

Which results in:
```
undefined method `array_type?' for nil:NilClass

          return unless node.first_argument.array_type?
                                           ^^^^^^^^^^^^
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-rspec-2.19.0/lib/rubocop/cop/rspec/match_array.rb:27:in `on_send'
```

<details>
<summary>Backtrace</summary>
An error occurred while RSpec/MatchArray cop was inspecting /Users/u0158204/code/karnov/pro/spec/services/content_references_migration/dk/migrate_content_reference_service_spec.rb:167:51.
undefined method `array_type?' for nil:NilClass

          return unless node.first_argument.array_type?
                                           ^^^^^^^^^^^^
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-rspec-2.19.0/lib/rubocop/cop/rspec/match_array.rb:27:in `on_send'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:143:in `public_send'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:143:in `block (2 levels) in trigger_restricted_cops'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:171:in `with_cop_error_handling'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:142:in `block in trigger_restricted_cops'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:141:in `each'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:141:in `trigger_restricted_cops'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:70:in `on_send'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:159:in `block in on_send'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:156:in `each'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:156:in `each_with_index'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:156:in `on_send'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:71:in `on_send'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:137:in `block in on_dstr'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:137:in `each'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:137:in `on_dstr'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:71:in `on_begin'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:158:in `on_block'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:71:in `on_block'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:158:in `on_block'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:71:in `on_block'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:137:in `block in on_dstr'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:137:in `each'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:137:in `on_dstr'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:71:in `on_begin'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:158:in `on_block'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:71:in `on_block'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:137:in `block in on_dstr'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:137:in `each'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:137:in `on_dstr'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:71:in `on_begin'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:158:in `on_block'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:71:in `on_block'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:137:in `block in on_dstr'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:137:in `each'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:137:in `on_dstr'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:71:in `on_begin'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:20:in `walk'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:87:in `investigate'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/team.rb:156:in `investigate_partial'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/team.rb:91:in `investigate'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:345:in `block in inspect_file'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:344:in `each'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:344:in `flat_map'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:344:in `inspect_file'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:287:in `block in do_inspection_loop'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:321:in `block in iterate_until_no_changes'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:314:in `loop'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:314:in `iterate_until_no_changes'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:283:in `do_inspection_loop'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:164:in `block in file_offenses'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:189:in `file_offense_cache'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:163:in `file_offenses'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:154:in `process_file'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:135:in `block in each_inspected_file'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:134:in `each'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:134:in `reduce'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:134:in `each_inspected_file'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:120:in `inspect_files'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:73:in `run'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli/command.rb:11:in `run'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli/environment.rb:18:in `run'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli.rb:118:in `run_command'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli.rb:125:in `execute_runners'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli.rb:51:in `block in run'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli.rb:77:in `profile_if_needed'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli.rb:43:in `run'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/exe/rubocop:19:in `block in <top (required)>'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/benchmark-0.2.1/lib/benchmark.rb:311:in `realtime'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/exe/rubocop:19:in `<top (required)>'
/Users/u0158204/.asdf/installs/ruby/3.1.3/bin/rubocop:25:in `load'
/Users/u0158204/.asdf/installs/ruby/3.1.3/bin/rubocop:25:in `<top (required)>'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/lib/bundler/cli/exec.rb:58:in `load'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/lib/bundler/cli/exec.rb:58:in `kernel_load'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/lib/bundler/cli/exec.rb:23:in `run'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/lib/bundler/cli.rb:491:in `exec'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/lib/bundler/cli.rb:34:in `dispatch'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/lib/bundler/cli.rb:28:in `start'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/exe/bundle:45:in `block in <top (required)>'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/Users/u0158204/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/exe/bundle:33:in `<top (required)>'
/Users/u0158204/.asdf/installs/ruby/3.1.3/bin/bundle:25:in `load'
/Users/u0158204/.asdf/installs/ruby/3.1.3/bin/bundle:25:in `<main>'
</details>

## Expected behavior
Not to fail.

## Actual behavior
Failed.

## Steps to reproduce the problem
`spec/test_spec.rb`:
```ruby
# frozen_string_literal: true

RSpec.describe "test" do
  let(:value) { [] }

  it "is empty" do
    expect(value).to match_array([])
  end
end
```

```
> bundle exec rubocop spec/test_spec.rb -a -d
For .: configuration from ./.rubocop.yml
Inheriting configuration from ./.rubocop_config.yml
configuration from ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-performance-1.16.0/config/default.yml
configuration from ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-performance-1.16.0/config/default.yml
Default configuration from ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/config/default.yml
configuration from ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-rails-2.18.0/config/default.yml
configuration from ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-rails-2.18.0/config/default.yml
configuration from ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-capybara-2.17.1/config/default.yml
configuration from ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-capybara-2.17.1/lib/../config/default.yml
configuration from ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-rspec-2.19.0/config/default.yml
configuration from ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-rspec-2.19.0/config/default.yml
Inheriting configuration from ./.rubocop_todo.yml
Use parallel by default.
Skipping parallel inspection: only a single file needs inspection
Inspecting 1 file
Scanning ./spec/test_spec.rb
Loading cache from .cache/rubocop_cache/886750e31dd700a20380b6a6ed8938201faebd01/8123c7090d4812cc10a91c1343176ff6e02c422b/326a6d9070747832f9b15781c4dbb2d4920af35a
An error occurred while RSpec/MatchArray cop was inspecting ./spec/test_spec.rb:7:21.
undefined method `array_type?' for nil:NilClass

          return unless node.first_argument.array_type?
                                           ^^^^^^^^^^^^
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-rspec-2.19.0/lib/rubocop/cop/rspec/match_array.rb:27:in `on_send'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:143:in `public_send'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:143:in `block (2 levels) in trigger_restricted_cops'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:171:in `with_cop_error_handling'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:142:in `block in trigger_restricted_cops'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:141:in `each'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:141:in `trigger_restricted_cops'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:70:in `on_send'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:159:in `block in on_send'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:156:in `each'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:156:in `each_with_index'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:156:in `on_send'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:71:in `on_send'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:158:in `on_block'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:71:in `on_block'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:137:in `block in on_dstr'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:137:in `each'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:137:in `on_dstr'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:71:in `on_begin'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:158:in `on_block'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:71:in `on_block'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:20:in `walk'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:87:in `investigate'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/team.rb:156:in `investigate_partial'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/team.rb:91:in `investigate'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:345:in `block in inspect_file'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:344:in `each'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:344:in `flat_map'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:344:in `inspect_file'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:287:in `block in do_inspection_loop'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:321:in `block in iterate_until_no_changes'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:314:in `loop'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:314:in `iterate_until_no_changes'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:283:in `do_inspection_loop'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:164:in `block in file_offenses'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:189:in `file_offense_cache'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:163:in `file_offenses'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:154:in `process_file'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:135:in `block in each_inspected_file'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:134:in `each'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:134:in `reduce'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:134:in `each_inspected_file'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:120:in `inspect_files'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:73:in `run'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli/command.rb:11:in `run'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli/environment.rb:18:in `run'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli.rb:118:in `run_command'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli.rb:125:in `execute_runners'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli.rb:51:in `block in run'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli.rb:77:in `profile_if_needed'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli.rb:43:in `run'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/exe/rubocop:19:in `block in <top (required)>'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/benchmark-0.2.1/lib/benchmark.rb:311:in `realtime'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/exe/rubocop:19:in `<top (required)>'
ruby/3.1.3/bin/rubocop:25:in `load'
ruby/3.1.3/bin/rubocop:25:in `<top (required)>'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/lib/bundler/cli/exec.rb:58:in `load'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/lib/bundler/cli/exec.rb:58:in `kernel_load'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/lib/bundler/cli/exec.rb:23:in `run'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/lib/bundler/cli.rb:491:in `exec'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/lib/bundler/cli.rb:34:in `dispatch'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/lib/bundler/cli.rb:28:in `start'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/exe/bundle:45:in `block in <top (required)>'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/exe/bundle:33:in `<top (required)>'
ruby/3.1.3/bin/bundle:25:in `load'
ruby/3.1.3/bin/bundle:25:in `<main>'
An error occurred while RSpec/MatchArray cop was inspecting ./spec/test_spec.rb:7:21.
undefined method `array_type?' for nil:NilClass

          return unless node.first_argument.array_type?
                                           ^^^^^^^^^^^^
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-rspec-2.19.0/lib/rubocop/cop/rspec/match_array.rb:27:in `on_send'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:143:in `public_send'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:143:in `block (2 levels) in trigger_restricted_cops'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:171:in `with_cop_error_handling'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:142:in `block in trigger_restricted_cops'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:141:in `each'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:141:in `trigger_restricted_cops'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:70:in `on_send'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:159:in `block in on_send'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:156:in `each'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:156:in `each_with_index'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:156:in `on_send'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:71:in `on_send'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:158:in `on_block'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:71:in `on_block'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:137:in `block in on_dstr'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:137:in `each'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:137:in `on_dstr'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:71:in `on_begin'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:158:in `on_block'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:71:in `on_block'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.27.0/lib/rubocop/ast/traversal.rb:20:in `walk'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/commissioner.rb:87:in `investigate'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/team.rb:156:in `investigate_partial'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cop/team.rb:91:in `investigate'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:345:in `block in inspect_file'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:344:in `each'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:344:in `flat_map'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:344:in `inspect_file'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:287:in `block in do_inspection_loop'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:321:in `block in iterate_until_no_changes'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:314:in `loop'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:314:in `iterate_until_no_changes'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:283:in `do_inspection_loop'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:164:in `block in file_offenses'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:189:in `file_offense_cache'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:163:in `file_offenses'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:154:in `process_file'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:135:in `block in each_inspected_file'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:134:in `each'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:134:in `reduce'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:134:in `each_inspected_file'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:120:in `inspect_files'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/runner.rb:73:in `run'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli/command.rb:11:in `run'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli/environment.rb:18:in `run'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli.rb:118:in `run_command'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli.rb:125:in `execute_runners'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli.rb:51:in `block in run'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli.rb:77:in `profile_if_needed'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/lib/rubocop/cli.rb:43:in `run'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/exe/rubocop:19:in `block in <top (required)>'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/benchmark-0.2.1/lib/benchmark.rb:311:in `realtime'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/exe/rubocop:19:in `<top (required)>'
ruby/3.1.3/bin/rubocop:25:in `load'
ruby/3.1.3/bin/rubocop:25:in `<top (required)>'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/lib/bundler/cli/exec.rb:58:in `load'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/lib/bundler/cli/exec.rb:58:in `kernel_load'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/lib/bundler/cli/exec.rb:23:in `run'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/lib/bundler/cli.rb:491:in `exec'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/lib/bundler/cli.rb:34:in `dispatch'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/lib/bundler/cli.rb:28:in `start'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/exe/bundle:45:in `block in <top (required)>'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.4.3/exe/bundle:33:in `<top (required)>'
ruby/3.1.3/bin/bundle:25:in `load'
ruby/3.1.3/bin/bundle:25:in `<main>'
C

Offenses:

spec/test_spec.rb:7:22: C: [Corrected] RSpec/ContainExactly: Prefer match_array when matching array values.
    expect(value).to contain_exactly()
                     ^^^^^^^^^^^^^^^^^
spec/test_spec.rb:7:22: C: [Corrected] RSpec/MatchArray: Prefer contain_exactly when matching an array literal.
    expect(value).to match_array([])
                     ^^^^^^^^^^^^^^^
spec/test_spec.rb:7:33: C: [Corrected] Style/MethodCallWithoutArgsParentheses: Do not use parentheses for method calls with no arguments.
    expect(value).to match_array()
                                ^^
spec/test_spec.rb:7:37: C: [Corrected] Style/MethodCallWithoutArgsParentheses: Do not use parentheses for method calls with no arguments.
    expect(value).to contain_exactly()
                                    ^^

1 file inspected, 4 offenses detected, 4 offenses corrected

2 errors occurred:
An error occurred while RSpec/MatchArray cop was inspecting ./spec/test_spec.rb:7:21.
An error occurred while RSpec/MatchArray cop was inspecting ./spec/test_spec.rb:7:21.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
https://github.com/rubocop/rubocop/issues

Mention the following information in the issue report:
1.48.0 (using Parser 3.2.1.1, rubocop-ast 1.27.0, running on ruby 3.1.3) [x86_64-darwin21]
Finished in 0.783444999717176 seconds
```

## RuboCop version

```
1.48.0 (using Parser 3.2.1.1, rubocop-ast 1.27.0, running on ruby 3.1.3) [x86_64-darwin21]
  - rubocop-performance 1.16.0
  - rubocop-rails 2.18.0
  - rubocop-rspec 2.19.0
```

### PR DESCRIPTION
**Pull request by bquorning**
When calling `match_array` with an empty array literal, you might as well use the simpler `eq` matcher with a `[]` argument.

Fixes #1591.
Closes #1592.
Closes #1594.

______________________________________________________________________

Before submitting the PR make sure the following are checked:

- [x] Feature branch is up-to-date with `master` (if not - rebase it).
- [x] Squashed related commits together.
- [x] Added tests.
- [x] Updated documentation.
- [x] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
- [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

### CODE REVIEW

**Comment by bquorning** [comment]
cc @ydah

**Review by nijikon — APPROVED** [review]

**Review by ydah — APPROVED** [review]
I think it looks good👍Thank you.

File: lib/rubocop/cop/rspec/match_array.rb [hunk 1]
```diff
@@ -20,11 +20,34 @@ module RSpec
       class MatchArray < Base
```
Comment (ydah) [inline lib/rubocop/cop/rspec/match_array.rb:20]: ask) How about adding bad/good cases?

Comment (bquorning) [reply lib/rubocop/cop/rspec/match_array.rb:20]: To documentation? Yeah, I should do that.

**Comment by bquorning** [comment]
@ydah Better now?

**Comment by ydah** [comment]
Thank you very much. Now it looks like we just need to update config/default.yml.

**Comment by bquorning** [comment]
Oh yeah, I forgot that 🤦🏼‍♂️ The PR should be ready now.

**Review by ydah — APPROVED** [review]
Thank you so much 🚀

**Comment by bquorning** [comment]
I changed some of the documentation and implementation to better match what you did in #1593 @ydah. Sorry, but please check one last time 🙏🏼

File: lib/rubocop/cop/rspec/match_array.rb [hunk 2]
```diff
@@ -17,14 +21,45 @@ module RSpec
...
       #   # good
       #   it { is_expected.to match_array(%w(tremble in fear foolish mortals)) }
+      #
+      #   # bad
+      #   it { is_expected.to match_array([]) }
+      #   it { is_expected.to match_array(%w[]) }
+      #
+      #   # good
+      #   it { is_expected.to eq([]) }
+      #   it { is_expected.to eq([]) }
```
Comment (ydah) [inline lib/rubocop/cop/rspec/match_array.rb:31]: imo) The good cases may be combined into one

File: lib/rubocop/cop/rspec/match_array.rb [hunk 3]
```diff
@@ -3,7 +3,11 @@
 module RuboCop
   module Cop
     module RSpec
-      # Prefer `contain_exactly` when matching an array literal.
+      # Checks where `match_array` is used.
+      #
+      # This cop checks for the following:
+      # - Prefer `contain_exactly` when matching an array with values.
+      # - Prefer `be_eq` when using `match_array` with an empty array literal.
```
Comment (ydah) [inline lib/rubocop/cop/rspec/match_array.rb:10]: Maybe `eq` instead of `be_eq`?

Comment (ydah) [reply lib/rubocop/cop/rspec/match_array.rb:10]:
```suggestion
      # - Prefer `eq` when using `match_array` with an empty array literal.
```

File: lib/rubocop/cop/rspec/match_array.rb (hunk 2 above)
Comment (ydah) [inline lib/rubocop/cop/rspec/match_array.rb:31]:
```suggestion
      #   # good
      #   it { is_expected.to eq([]) }
```

File: lib/rubocop/cop/rspec/match_array.rb [hunk 4]
```diff
@@ -17,14 +21,44 @@ module RSpec
       #
       #   # good
       #   it { is_expected.to match_array(%w(tremble in fear foolish mortals)) }
+      #
+      #   # bad
+      #   it { is_expected.to match_array([]) }
+      #   it { is_expected.to match_array(%w[]) }
```
Comment (ydah) [inline lib/rubocop/cop/rspec/match_array.rb:27]: I had overlooked this 🙇‍♂️ I think this is the last one.
```suggestion
      #   it { is_expected.to match_array(%w()) }
      #   it { is_expected.to match_array(%i()) }
```

Comment (bquorning) [reply lib/rubocop/cop/rspec/match_array.rb:27]: There is also `%W` and `%I`. I meant to give only a few examples and not an exhaustive list :-)

As for `%w[]` vs `%w()`, [RuboCop defaults to enforcing](https://github.com/rubocop/rubocop/blob/856d73c467ddd07dcaa74a0f88aa94ae5ba4172a/config/default.yml#L4685-L4700) `[]`.

I hope it’s ok if I keep the PR as-is.
