### PR TITLE
[Fix #1342] Fix a false negative for `RSpec/Capybara/SpecificMatcher` for `have_field`.

### LINKED ISSUE #1342: [RSpec/Capybara/SpecificMatcher] False-negative for `have_field`
[has_field](https://www.rubydoc.info/gems/capybara/Capybara/Node/Matchers#has_field%3F-instance_method) handles a bunch of cases which can replace for example:

```rb
expect(page).to have_css('input')
expect(page).to have_css('input[type="checkbox"]')
expect(page).to have_css('textarea')
# etc
```

Same for the negative cases - `expect(page).to have_no_css('input')`.

cc @ydah 

P.S. Also:

```rb
# bad
expect(find('input').value).to eq('foobar')
# good
expect(page).to have_field(with: 'foobar')
```

Or something.

### PR DESCRIPTION
**Pull request by ydah**
This PR is fix a false negative for `RSpec/Capybara/SpecificMatcher` for `have_field`.

Resolve part of the issue: https://github.com/rubocop/rubocop-rspec/issues/1342

```ruby
expect(page).to have_css('input')
expect(page).to have_css('input[type="checkbox"]')
expect(page).to have_css('textarea')
```

---

Before submitting the PR make sure the following are checked:

* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Updated documentation.
* [x] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
* [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

If you have created a new cop:

* [-] Added the new cop to `config/default.yml`.
* [-] The cop is configured as `Enabled: pending` in `config/default.yml`.
* [-] The cop is configured as `Enabled: true` in `.rubocop.yml`.
* [-] The cop documents examples of good and bad code.
* [-] The tests assert both that bad code is reported and that good code is not reported.
* [-] Set `VersionAdded` in `default/config.yml` to the next minor version.

If you have modified an existing cop's configuration options:

* [-] Set `VersionChanged` in `config/default.yml` to the next major version.

### CODE REVIEW

**Comment by ydah** [comment]
Thank you so much!

```ruby
expect(page).to have_css('input')
expect(page).to have_css('input[type="checkbox"]')
expect(page).to have_css('textarea')
# etc
```
This one has created a PR: https://github.com/rubocop/rubocop-rspec/pull/1343 .

```ruby
# bad
expect(find('input').value).to eq('foobar')
# good
expect(page).to have_field(with: 'foobar')
```
This one but I am inclined to put something else cop in charge of this one instead of `SpecificMatcher`.

File: spec/rubocop/cop/rspec/capybara/specific_matcher_spec.rb [hunk 1]
```diff
@@ -134,10 +134,26 @@ class style visible obscured exact exact_text normalize_ws match wait
...
+
+  %i[above below left_of right_of near count minimum maximum between
+     text id class style visible obscured exact exact_text normalize_ws
+     match wait filter_set checked unchecked disabled valid name
+     placeholder validation_message ].each do |attr|
+    it 'registers an offense for abstract matcher when ' \
+       "first argument is element with replaceable attributes #{attr} " \
+       'for `have_field`' do
+      expect_offense(<<-RUBY, attr: attr)
+     expect(page).to have_css("input[#{attr}=foo]")
```
Comment (Darhazer) [inline spec/rubocop/cop/rspec/capybara/specific_matcher_spec.rb:153]: the spacing seems off

File: spec/rubocop/cop/rspec/capybara/specific_matcher_spec.rb [hunk 2]
```diff
@@ -134,10 +134,26 @@ class style visible obscured exact exact_text normalize_ws match wait
        "first argument is element with replaceable attributes #{attr} " \
        'for `have_select`' do
       expect_offense(<<-RUBY, attr: attr)
-        expect(page).to have_css("select[#{attr}=foo]")
-                        ^^^^^^^^^^^^^^^^^^{attr}^^^^^^^ Prefer `have_select` over `have_css`.
-        expect(page).to have_css("select[#{attr}]")
-                        ^^^^^^^^^^^^^^^^^^{attr}^^^ Prefer `have_select` over `have_css`.
+       expect(page).to have_css("select[#{attr}=foo]")
```
Comment (Darhazer) [inline spec/rubocop/cop/rspec/capybara/specific_matcher_spec.rb:137]: this change should not be necessary

**Comment by ydah** [comment]
Thanks for the review. I have updated this PR.

**Review by Darhazer — APPROVED** [review]
Thank you
