### PR TITLE
RSpec/UnspecifiedException: break on non-send blocks to avoid false positives on functions named `raise_exception`

### LINKED ISSUE #1949: RSpec/UnspecifiedException appears to trigger if the subject function is named `raise_exception`
It seems like the `RSpec/UnspecifiedException` cop should not be triggered on the following code, but it is:

```ruby
require "spec_helper"

class Foo

  def raise_exception
    raise StandardError, "huh"
  end

end

describe Foo do
  let(:subject) { described_class.new }

  describe "#raise_exception" do
    it "throws a StandardError" do
      expect { subject.raise_exception }.to raise_error(StandardError)
    end
  end
end

``` 

In particular, the cop highlights `subject.raise_exception` as violating the cop, which doesn't make sense - the cop should be looking it how we _handle_ the exception, yeah?

### PR DESCRIPTION
**Pull request by aarestad**
Fixes a false positive in the `UnspecifiedException` cop that is triggered when a function under test is literally called `raise_exception` or `raise_error`.

Resolves #1949.

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -24,4 +24,7 @@ coverage
 # vscode generated
 .vscode
 
+# IntelliJ generated
+.idea
```
Comment (bquorning) [inline .gitignore:28]: This line belongs in your `~/.gitignore` and not here.

**Review by bquorning — APPROVED** [review]

File: lib/rubocop/cop/rspec/unspecified_exception.rb [hunk 2]
```diff
@@ -62,7 +62,11 @@ def empty_exception_matcher?(node)
         end
 
         def find_expect_to(node)
-          node.each_ancestor(:send).find do |ancestor|
+          node.each_ancestor.find do |ancestor|
+            break if ancestor.block_type?
+
```
Comment (bquorning) [inline lib/rubocop/cop/rspec/unspecified_exception.rb:67]: Sorry, I’m nitpicking now :-)
```suggestion
```

**Comment by bquorning** [comment]
Can I ask you for a review @pirj ?

File: CHANGELOG.md [hunk 3]
```diff
@@ -2,6 +2,8 @@
 
 ## Master (Unreleased)
 
+- Fix false-positive for `RSpec/UnspecifiedException` when a function is literally named `raise_exception`. ([@aarestad])
```
Comment (pirj) [inline CHANGELOG.md:5]: Function -> method

is this the only problem this pr fixes?

**Review by pirj — APPROVED** [review]
Does it fix #1954, too? Can you please add a spec and a changelog entry, or remove this mention from the pr description?

I’d say the cop should be disabled and deprecated, but if you’re fine with fizing it, I have no objections, too.

Thank you!

File: CHANGELOG.md (hunk 3 above)
Comment (aarestad) [reply CHANGELOG.md:5]: Yeah, I'll remove the reference to the other issue since I don't really know anything about it other than that comment.

Comment (aarestad) [inline CHANGELOG.md:5]:
```suggestion
- Fix false-positive for `RSpec/UnspecifiedException` when a method is literally named `raise_exception`. ([@aarestad])
```

Comment (G-Rath) [reply CHANGELOG.md]: just confirming once this is landed I'm happy to do a follow-up to get my issue closed by e.g. adding a spec, so I support you pretending it doesn't exist 🙂

File: spec/rubocop/cop/rspec/unspecified_exception_spec.rb [hunk 4]
```diff
@@ -198,5 +198,29 @@
...
+      expect_no_offenses(<<~RUBY)
+        def raise_error
+          raise StandardError
+        end
+
+        expect {
+          raise_error
+        }.to raise_exception(StandardError)
+      RUBY
+    end
```
Comment (bquorning) [inline spec/rubocop/cop/rspec/unspecified_exception_spec.rb:224]: I just noticed that this spec file has a context named `'with raise_error matcher'`. So this example should probably be moved to around line 88 or so.

**Review by bquorning — APPROVED** [review]
One final nitpick from me 😬

File: spec/rubocop/cop/rspec/unspecified_exception_spec.rb (hunk 4 above)
Comment (bquorning) [reply spec/rubocop/cop/rspec/unspecified_exception_spec.rb:224]: Oh, also please squash the commits (as I imagine we are getting close to merging now).

**Review by bquorning — APPROVED** [review]
